name: Publish Rust crate

on:
  workflow_call:
    inputs:
      crate-name:
        required: true
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs:
      - should-publish
      - pre-publish-checks
    if: needs.should-publish.outputs.is_new_version == 'yes' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          echo "${{ toJSON(inputs) }}"
          echo "${{ toJSON(github.event.inputs) }}"

      - name: Tag the version
        run: |
          set -euxo pipefail
          export CURRENT_VERSION="$(.github/workflows/get_current_crate_version.sh ${{ inputs.crate-name }})"
          git tag "${{ inputs.crate-name }}-v$CURRENT_VERSION"
          git push origin "${{ inputs.crate-name }}-v$CURRENT_VERSION"

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CARGO_REGISTRY_TOKEN }}"
        run: cargo publish

  should-publish:
    name: Check if version changed
    runs-on: ubuntu-latest
    outputs:
      is_new_version: "${{ steps.check.outputs.is_new_version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: check
        run: |
          set +e
          .github/workflows/is_crate_version_already_uploaded.sh ${{ inputs.crate-name }}
          export EXIT_CODE="$?"
          set -e
          if [[ "$EXIT_CODE" == "7" ]]; then
            echo '::set-output name=is_new_version::no'
          elif [[ "$EXIT_CODE" == "0" ]]; then
            echo '::set-output name=is_new_version::yes'
          else
            # Unexpected outcome, indicates a bug.
            exit "$EXIT_CODE"
          fi

  pre-publish-checks:
    name: Check for semver compliance
    runs-on: ubuntu-latest
    needs:
      - should-publish
    if: needs.should-publish.outputs.is_new_version == 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v1
        with:
          crate-name: "${{ inputs.crate-name }}"
          version-tag-prefix: "${{ inputs.crate-name }}-v"
