from typing import Any, Dict, Iterator, Mapping

class AdapterShim:
    def __init__(self, adapter: Any) -> None: ...

class InvalidSchemaError(Exception): ...
class ParseError(Exception): ...
class ValidationError(Exception): ...
class FrontendError(Exception): ...
class InvalidIRQueryError(Exception): ...
class QueryArgumentsError(Exception): ...

class Schema:
    def __init__(self, schema_txt: str): ...

def interpret_query(
    adapter: AdapterShim, schema: Schema, query: str, arguments: Mapping[str, Any]
) -> Iterator[Dict[str, Any]]: ...
