[package]
name = "trustfall"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
trustfall_core = { path = "../trustfall_core", version = "0.1.1" }
