[package]
name = "trustfall"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
trustfall_core = { version = "0.2.0", path = "../trustfall_core" }
trustfall_derive = { version = "0.2.0", path = "../trustfall_derive" }
