allowed_external_types = [
    "anyhow::Result",
    "trustfall_core::accessor_property",
    "trustfall_core::field_property",
    "trustfall_core::interpreter::Adapter",
    "trustfall_core::interpreter::basic_adapter::BasicAdapter",
    "trustfall_core::interpreter::ContextIterator",
    "trustfall_core::interpreter::ContextOutcomeIterator",
    "trustfall_core::interpreter::DataContext",
    "trustfall_core::interpreter::helpers::correctness::check_adapter_invariants",
    "trustfall_core::interpreter::helpers::resolve_coercion_using_schema",
    "trustfall_core::interpreter::helpers::resolve_coercion_with",
    "trustfall_core::interpreter::helpers::resolve_neighbors_with",
    "trustfall_core::interpreter::helpers::resolve_property_with",
    "trustfall_core::interpreter::helpers::resolve_typename",
    "trustfall_core::interpreter::hints::candidates::CandidateValue",
    "trustfall_core::interpreter::hints::candidates::Range",
    "trustfall_core::interpreter::hints::dynamic::DynamicallyResolvedValue",
    "trustfall_core::interpreter::hints::EdgeInfo",
    "trustfall_core::interpreter::hints::QueryInfo",
    "trustfall_core::interpreter::hints::ResolveEdgeInfo",
    "trustfall_core::interpreter::hints::ResolveInfo",
    "trustfall_core::interpreter::hints::vertex_info::VertexInfo",
    "trustfall_core::interpreter::Typename",
    "trustfall_core::interpreter::VertexIterator",
    "trustfall_core::interpreter::VertexIterator",
    "trustfall_core::ir::EdgeParameters",
    "trustfall_core::ir::Eid",
    "trustfall_core::ir::value::FieldValue",
    "trustfall_core::ir::value::TransparentValue",
    "trustfall_core::ir::Vid",
    "trustfall_core::schema::adapter::SchemaAdapter",
    "trustfall_core::schema::Schema",
    "trustfall_core::serialization::TryIntoStruct",
    "trustfall_derive::TrustfallEnumVertex",
    "trustfall_derive::Typename",
    "trustfall::provider::resolve_neighbors_with",
]
